version: "3.9"

volumes:
  postgres_volume_local:

services:
  pg_local:
    image: postgres:14-alpine3.17
    env_file:
      - local.env
    ports:
      - "54321:5432"
    volumes:
      - "postgres_volume_local:/var/lib/postgresql/data"


  migrator:
    build:
      context: .
      dockerfile: migration.Dockerfile
    env_file:
      - local.env
    environment:
      - PG_HOST=pg_local
    depends_on:
      - pg_local
    restart: on-failure
    

  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - local.env
    depends_on:
      - pg_local
      - migrator
    ports:
      - "50051:50051"